/**
 * Map of static tokens to their values
 */
export const StaticTokenMap = {
  'border-width-default': '1px',
  'border-width-input': '2px',
  'border-width-input-overlay-unfocused': '1px',
  'border-width-marked': '3px',
  'border-width-spinner': '2px',
  'border-width-tag': '2px',
  'border-radius-none': '0',
  'border-radius-small': '0.2rem',
  'border-radius-medium': '0.4rem',
  'border-radius-large': '0.6rem',
  'border-radius-extra-large': '1rem',
  'border-radius-extra-extra-large': '1.6rem',
  'border-radius-rounded': '9000px',
  'break-xs': '480px',
  'break-sm': '768px',
  'break-md': '1024px',
  'break-lg': '1200px',
  'break-xl': '1440px',
  'break-xxl': '1600px',
  'color-brand-muted-ice': '#e0ebff',
  'color-brand-muted-cupcake': '#ffa3ee',
  'color-brand-muted-mint': '#8fffd2',
  'color-brand-muted-sky': '#7aa7ff',
  'color-brand-muted-blush': '#ffcdcc',
  'color-brand-muted-canary': '#f5f500',
  'color-brand-muted-smoke': '#d3d3d9',
  'color-brand-muted-lavender': '#d1b3ff',
  'color-brand-muted-mustard': '#ffd37a',
  'color-brand-muted-emerald': '#00f593',
  'color-brand-muted-coral': '#ff8280',
  'color-brand-muted-ocean': '#1345aa',
  'color-brand-accent-grape': '#5c16c5',
  'color-brand-accent-dragonfruit': '#ff38db',
  'color-brand-accent-carrot': '#e69900',
  'color-brand-accent-sun': '#f5f500',
  'color-brand-accent-lime': '#00f593',
  'color-brand-accent-turquoise': '#00f0f0',
  'color-brand-accent-eggplant': '#451093',
  'color-brand-accent-wine': '#ae1392',
  'color-brand-accent-slime': '#00f593',
  'color-brand-accent-seafoam': '#8fffd2',
  'color-brand-accent-cherry': '#eb0400',
  'color-brand-accent-marine': '#1f69ff',
  'color-brand-accent-seaweed': '#00a3a3',
  'color-brand-accent-pebble': '#848494',
  'color-brand-accent-moon': '#efeff1',
  'color-brand-accent-fiji': '#8fffd2',
  'color-brand-accent-blueberry': '#1f69ff',
  'color-brand-accent-arctic': '#00f0f0',
  'color-brand-accent-highlighter': '#f5f500',
  'color-brand-accent-flamingo': '#ff38db',
  'color-brand-accent-ruby': '#eb0400',
  'color-brand-accent-punch': '#ffcdcc',
  'color-brand-accent-creamsicle': '#ffd37a',
  'color-white': '#ffffff',
  'color-black': '#000000',
  'color-red': '#e91916',
  'color-red-darker': '#bb1411',
  'color-orange': '#ffd37a',
  'color-yellow': '#ffd37a',
  'color-green': '#00f593',
  'color-green-darker': '#00ad96',
  'color-blue': '#1f69ff',
  'color-prime-blue': '#0e9bd8',
  'color-magenta': '#c53dff',
  'color-error': '#eb0400',
  'color-warn': '#ffd37a',
  'color-success': '#00f593',
  'color-info': '#1f69ff',
  'color-accent': '#9147ff',
  'color-twitch-purple': '#9147ff',
  'color-twitch-purple-1': '#040109',
  'color-twitch-purple-2': '#0d031c',
  'color-twitch-purple-3': '#15052e',
  'color-twitch-purple-4': '#24094e',
  'color-twitch-purple-5': '#330c6e',
  'color-twitch-purple-6': '#451093',
  'color-twitch-purple-7': '#5c16c5',
  'color-twitch-purple-8': '#772ce8',
  'color-twitch-purple-9': '#9147ff',
  'color-twitch-purple-10': '#a970ff',
  'color-twitch-purple-11': '#bf94ff',
  'color-twitch-purple-12': '#d1b3ff',
  'color-twitch-purple-13': '#e3d1ff',
  'color-twitch-purple-14': '#f0e5ff',
  'color-twitch-purple-15': '#fcfaff',
  'color-hinted-grey-1': '#0e0e10',
  'color-hinted-grey-2': '#18181b',
  'color-hinted-grey-3': '#1f1f23',
  'color-hinted-grey-4': '#26262c',
  'color-hinted-grey-5': '#323239',
  'color-hinted-grey-6': '#3b3b44',
  'color-hinted-grey-7': '#53535f',
  'color-hinted-grey-8': '#848494',
  'color-hinted-grey-9': '#adadb8',
  'color-hinted-grey-10': '#c8c8d0',
  'color-hinted-grey-11': '#d3d3d9',
  'color-hinted-grey-12': '#dedee3',
  'color-hinted-grey-13': '#e6e6ea',
  'color-hinted-grey-14': '#efeff1',
  'color-hinted-grey-15': '#f7f7f8',
  'color-transparent': 'rgba(0, 0, 0, 0)',
  'color-opac-b-1': 'rgba(0, 0, 0, 0.05)',
  'color-opac-b-2': 'rgba(0, 0, 0, 0.1)',
  'color-opac-b-3': 'rgba(0, 0, 0, 0.15)',
  'color-opac-b-4': 'rgba(0, 0, 0, 0.2)',
  'color-opac-b-5': 'rgba(0, 0, 0, 0.25)',
  'color-opac-b-6': 'rgba(0, 0, 0, 0.3)',
  'color-opac-b-7': 'rgba(0, 0, 0, 0.4)',
  'color-opac-b-8': 'rgba(0, 0, 0, 0.5)',
  'color-opac-b-9': 'rgba(0, 0, 0, 0.6)',
  'color-opac-b-10': 'rgba(0, 0, 0, 0.7)',
  'color-opac-b-11': 'rgba(0, 0, 0, 0.75)',
  'color-opac-b-12': 'rgba(0, 0, 0, 0.8)',
  'color-opac-b-13': 'rgba(0, 0, 0, 0.85)',
  'color-opac-b-14': 'rgba(0, 0, 0, 0.9)',
  'color-opac-b-15': 'rgba(0, 0, 0, 0.95)',
  'color-opac-w-1': 'rgba(255, 255, 255, 0.05)',
  'color-opac-w-2': 'rgba(255, 255, 255, 0.1)',
  'color-opac-w-3': 'rgba(255, 255, 255, 0.15)',
  'color-opac-w-4': 'rgba(255, 255, 255, 0.2)',
  'color-opac-w-5': 'rgba(255, 255, 255, 0.25)',
  'color-opac-w-6': 'rgba(255, 255, 255, 0.3)',
  'color-opac-w-7': 'rgba(255, 255, 255, 0.4)',
  'color-opac-w-8': 'rgba(255, 255, 255, 0.5)',
  'color-opac-w-9': 'rgba(255, 255, 255, 0.6)',
  'color-opac-w-10': 'rgba(255, 255, 255, 0.7)',
  'color-opac-w-11': 'rgba(255, 255, 255, 0.75)',
  'color-opac-w-12': 'rgba(255, 255, 255, 0.8)',
  'color-opac-w-13': 'rgba(255, 255, 255, 0.85)',
  'color-opac-w-14': 'rgba(255, 255, 255, 0.9)',
  'color-opac-w-15': 'rgba(255, 255, 255, 0.95)',
  'color-opac-p-1': 'rgba(92, 22, 197, 0.05)',
  'color-opac-p-2': 'rgba(92, 22, 197, 0.1)',
  'color-opac-p-3': 'rgba(92, 22, 197, 0.15)',
  'color-opac-p-4': 'rgba(92, 22, 197, 0.2)',
  'color-opac-p-5': 'rgba(92, 22, 197, 0.25)',
  'color-opac-p-6': 'rgba(92, 22, 197, 0.3)',
  'color-opac-p-7': 'rgba(92, 22, 197, 0.4)',
  'color-opac-p-8': 'rgba(92, 22, 197, 0.5)',
  'color-opac-p-9': 'rgba(92, 22, 197, 0.6)',
  'color-opac-p-10': 'rgba(92, 22, 197, 0.7)',
  'color-opac-p-11': 'rgba(92, 22, 197, 0.75)',
  'color-opac-p-12': 'rgba(92, 22, 197, 0.8)',
  'color-opac-p-13': 'rgba(92, 22, 197, 0.85)',
  'color-opac-p-14': 'rgba(92, 22, 197, 0.9)',
  'color-opac-p-15': 'rgba(92, 22, 197, 0.95)',
  'color-orange-1': '#050301',
  'color-orange-2': '#090601',
  'color-orange-3': '#120d02',
  'color-orange-4': '#251a04',
  'color-orange-5': '#372706',
  'color-orange-6': '#453008',
  'color-orange-7': '#65470b',
  'color-orange-8': '#7c570e',
  'color-orange-9': '#9e6900',
  'color-orange-10': '#c28100',
  'color-orange-11': '#e69900',
  'color-orange-12': '#ffb31a',
  'color-orange-13': '#ffd37a',
  'color-orange-14': '#ffe5b3',
  'color-orange-15': '#fffaf0',
  'color-yellow-1': '#050501',
  'color-yellow-2': '#090901',
  'color-yellow-3': '#0e0e02',
  'color-yellow-4': '#1c1c03',
  'color-yellow-5': '#292905',
  'color-yellow-6': '#373706',
  'color-yellow-7': '#4e4e09',
  'color-yellow-8': '#60600b',
  'color-yellow-9': '#7a7a00',
  'color-yellow-10': '#949400',
  'color-yellow-11': '#adad00',
  'color-yellow-12': '#c7c700',
  'color-yellow-13': '#e0e000',
  'color-yellow-14': '#f5f500',
  'color-yellow-15': '#ffffc7',
  'color-green-1': '#010503',
  'color-green-2': '#010906',
  'color-green-3': '#02120c',
  'color-green-4': '#042015',
  'color-green-5': '#063221',
  'color-green-6': '#074029',
  'color-green-7': '#0a5738',
  'color-green-8': '#016b40',
  'color-green-9': '#018852',
  'color-green-10': '#00a865',
  'color-green-11': '#00c274',
  'color-green-12': '#00db84',
  'color-green-13': '#00f593',
  'color-green-14': '#8fffd2',
  'color-green-15': '#ebfff7',
  'color-cyan-1': '#010505',
  'color-cyan-2': '#010909',
  'color-cyan-3': '#021212',
  'color-cyan-4': '#042020',
  'color-cyan-5': '#052e2e',
  'color-cyan-6': '#073c3c',
  'color-cyan-7': '#095353',
  'color-cyan-8': '#0c6a6a',
  'color-cyan-9': '#018383',
  'color-cyan-10': '#00a3a3',
  'color-cyan-11': '#00b8b8',
  'color-cyan-12': '#00d6d6',
  'color-cyan-13': '#00f0f0',
  'color-cyan-14': '#6bffff',
  'color-cyan-15': '#ebffff',
  'color-blue-1': '#010205',
  'color-blue-2': '#020712',
  'color-blue-3': '#040d20',
  'color-blue-4': '#071a40',
  'color-blue-5': '#0a255c',
  'color-blue-6': '#0d3177',
  'color-blue-7': '#1345aa',
  'color-blue-8': '#1756d3',
  'color-blue-9': '#1f69ff',
  'color-blue-10': '#528bff',
  'color-blue-11': '#7aa7ff',
  'color-blue-12': '#a3c2ff',
  'color-blue-13': '#c7daff',
  'color-blue-14': '#e0ebff',
  'color-blue-15': '#fafcff',
  'color-magenta-1': '#050104',
  'color-magenta-2': '#12020f',
  'color-magenta-3': '#20041b',
  'color-magenta-4': '#37062e',
  'color-magenta-5': '#4e0941',
  'color-magenta-6': '#650b55',
  'color-magenta-7': '#8a0f73',
  'color-magenta-8': '#ae1392',
  'color-magenta-9': '#c516a5',
  'color-magenta-10': '#ff38db',
  'color-magenta-11': '#ff75e6',
  'color-magenta-12': '#ffa3ee',
  'color-magenta-13': '#ffc7f5',
  'color-magenta-14': '#ffe0f9',
  'color-magenta-15': '#fffafe',
  'color-red-1': '#050101',
  'color-red-2': '#120202',
  'color-red-3': '#200404',
  'color-red-4': '#3c0807',
  'color-red-5': '#530a09',
  'color-red-6': '#6e0e0c',
  'color-red-7': '#971311',
  'color-red-8': '#bb1411',
  'color-red-9': '#eb0400',
  'color-red-10': '#ff4f4d',
  'color-red-11': '#ff8280',
  'color-red-12': '#ffaaa8',
  'color-red-13': '#ffcdcc',
  'color-red-14': '#ffe6e5',
  'color-red-15': '#fffafa',
  'color-twitter': '#1da1f2',
  'color-facebook': '#3b5998',
  'color-reddit': '#ff4500',
  'color-snapchat': '#fffc00',
  'color-instagram': '#405de6',
  'color-youtube': '#cd201f',
  'color-paypal': '#009cde',
  'color-paypal-blue': '#009cde',
  'color-paypal-yellow': '#fcc439',
  'color-vk': '#45668e',
  'color-amazon': '#fad677',
  'button-size-small': '2.4rem',
  'button-size-default': '3rem',
  'button-size-large': '3.6rem',
  'button-text-small': '1.2rem',
  'button-text-default': '1.3rem',
  'button-text-large': '1.4rem',
  'button-padding-x': '1rem',
  'button-padding-y': '0.5rem',
  'input-size-small': '2.4rem',
  'input-size-default': '3rem',
  'input-size-large': '3.6rem',
  'font-base':
    '"Inter", "Roobert", "Helvetica Neue", Helvetica, Arial, sans-serif',
  'font-display':
    '"Roobert", "Inter", "Helvetica Neue", Helvetica, Arial, sans-serif',
  'font-mono': 'monospace',
  'font-size-1': '5.4rem',
  'font-size-2': '3.6rem',
  'font-size-3': '2.4rem',
  'font-size-4': '1.8rem',
  'font-size-5': '1.4rem',
  'font-size-6': '1.3rem',
  'font-size-7': '1.2rem',
  'font-size-8': '1.2rem',
  'font-size-base': '1.3rem',
  'font-weight-normal': 400,
  'font-weight-semibold': 600,
  'font-weight-bold': 700,
  'font-weight-hdr': 400,
  'line-height-body': 1.5,
  'line-height-heading': 1.2,
  'base-rem-unit': 10,
  'grid-columns': 12,
  'grid-gutter-width': '1.5rem',
  'grid-gutter-width-lg': '2rem',
  'grid-gutter-width-sm': '1rem',
  'grid-gutter-width-xs': '0.5rem',
  'opac-1': 0.05,
  'opac-2': 0.1,
  'opac-3': 0.15,
  'opac-4': 0.2,
  'opac-5': 0.25,
  'opac-6': 0.3,
  'opac-7': 0.4,
  'opac-8': 0.5,
  'opac-9': 0.6,
  'opac-10': 0.7,
  'opac-11': 0.75,
  'opac-12': 0.8,
  'opac-13': 0.85,
  'opac-14': 0.9,
  'opac-15': 0.95,
  'space-0': 0,
  'space-1': '1rem',
  'space-2': '2rem',
  'space-3': '3rem',
  'space-4': '4rem',
  'space-5': '5rem',
  'space-6': '6rem',
  'space-7': '7rem',
  'space-8': '8rem',
  'space-9': '9rem',
  'space-10': '10rem',
  'space-auto': 'auto',
  'space-05': '0.5rem',
  'timing-short': '100ms',
  'timing-medium': '250ms',
  'timing-long': '300ms',
  'z-index-modal': 5000,
  'z-index-notification': 4000,
  'z-index-overlay': 3000,
  'z-index-balloon': 2000,
  'z-index-sticky': 1000,
  'z-index-above': 10,
  'z-index-default': 1,
  'z-index-below': -1,
};

/**
 * Map of theme tokens to their dark values
 */
export const DarkThemeMap = {
  'color-background-button': '#5c16c5',
  'color-background-button-hover': '#772ce8',
  'color-background-button-focus': '#772ce8',
  'color-background-button-active': '#5c16c5',
  'color-background-button-purchase': 'rgba(0, 0, 0, 0.25)',
  'color-background-button-status': '#00db84',
  'color-background-button-status-hover': '#ffaaa8',
  'color-background-button-status-focus': '#ffaaa8',
  'color-background-button-status-active': '#ff4f4d',
  'color-background-button-success-focus': '#00ad96',
  'color-background-button-alert': '#e91916',
  'color-background-button-alert-hover': '#bb1411',
  'color-background-button-alert-focus': '#bb1411',
  'color-background-button-alert-active': '#e91916',
  'color-background-button-overlay': 'rgba(0, 0, 0, 0)',
  'color-background-button-overlay-hover': 'rgba(255, 255, 255, 0.05)',
  'color-background-button-overlay-focus': 'rgba(255, 255, 255, 0.05)',
  'color-background-button-overlay-active': 'transparent',
  'color-background-interactable-alpha-hover': 'rgba(255, 255, 255, 0.2)',
  'color-background-interactable-alpha-active': 'rgba(255, 255, 255, 0.25)',
  'color-background-interactable-alpha-selected': 'rgba(255, 255, 255, 0.15)',
  'color-text-button': '#ffffff',
  'color-text-button-hover': '#ffffff',
  'color-text-button-focus': '#ffffff',
  'color-text-button-active': '#ffffff',
  'color-text-button-secondary-hover': '#3b3b44',
  'color-text-button-secondary-focus': '#3b3b44',
  'color-text-button-secondary-active': '#3b3b44',
  'color-text-button-text-hover': 'rgba(255, 255, 255, 0.05)',
  'color-text-button-text-focus': 'rgba(255, 255, 255, 0.05)',
  'color-text-button-text-active': 'rgba(92, 22, 197, 0.1)',
  'color-text-button-status': '#ffffff',
  'color-text-button-status-hover': '#ffffff',
  'color-text-button-status-focus': '#ffffff',
  'color-text-button-status-active': '#ffffff',
  'color-text-button-success-hover': '#000000',
  'color-text-button-success-focus': '#000000',
  'color-text-button-success-active': '#000000',
  'color-text-button-alert': '#000000',
  'color-text-button-alert-hover': '#000000',
  'color-text-button-alert-focus': '#000000',
  'color-text-button-alert-active': '#000000',
  'color-text-button-overlay': '#ffffff',
  'color-text-button-overlay-hover': '#ffffff',
  'color-text-button-overlay-focus': '#ffffff',
  'color-text-button-overlay-active': '#ffffff',
  'color-text-interactable': 'currentColor',
  'color-text-interactable-hover': '#ffffff',
  'color-text-interactable-active': '#ffffff',
  'color-text-interactable-inverted': '#ffffff',
  'color-text-input-focus': 'transparent',
  'color-border-button': '#5c16c5',
  'color-border-button-hover': '#772ce8',
  'color-border-button-focus': '#9147ff',
  'color-border-button-active': '#772ce8',
  'color-border-button-disabled': 'rgba(255, 255, 255, 0.05)',
  'color-border-button-status': '#00f593',
  'color-border-button-status-hover': '#bb1411',
  'color-border-button-status-focus': '#bb1411',
  'color-border-button-status-active': '#e91916',
  'color-border-button-success': '#00f593',
  'color-border-button-success-hover': '#00f593',
  'color-border-button-success-focus': '#00f593',
  'color-border-button-success-active': '#00f593',
  'color-border-button-alert': '#e91916',
  'color-border-button-alert-hover': '#bb1411',
  'color-border-button-alert-focus': '#bb1411',
  'color-border-button-alert-active': '#e91916',
  'color-border-button-overlay': 'rgba(0, 0, 0, 0)',
  'color-border-button-overlay-hover': 'rgba(0, 0, 0, 0)',
  'color-border-button-overlay-focus': 'rgba(255, 255, 255, 0.3)',
  'color-border-button-overlay-active': 'rgba(255, 255, 255, 0.6)',
  'color-border-button-overlay-bordered': '#ffffff',
  'color-border-interactable-selected': '#a970ff',
  'shadow-input': 'inset 0 0 0 1px #330c6e',
  'shadow-input-error': '0 0 0 1px #ff4f4d',
  'shadow-input-focus': '0 0 10px -2px #a970ff',
  'shadow-input-error-focus': '0 0 6px -2px #ff4f4d',
  'shadow-interactable-focus': '0 0 6px 0 #772ce8',
  'color-background-subscriber-stream-tag-default': '#24094e',
  'color-background-subscriber-stream-tag-hover': '#15052e',
  'color-background-subscriber-stream-tag-active': '#24094e',
  'color-border-subscriber-stream-tag': '#330c6e',
  'color-background-body': '#0e0e10',
  'color-background-base': '#18181b',
  'color-background-alt': '#1f1f23',
  'color-background-alt-2': '#26262c',
  'color-background-float': '#1f1f23',
  'color-background-accent': '#772ce8',
  'color-background-accent-alt': '#5c16c5',
  'color-background-accent-alt-2': '#451093',
  'color-background-placeholder': 'rgba(255, 255, 255, 0.05)',
  'color-background-overlay-placeholder': 'rgba(255, 255, 255, 0.15)',
  'color-background-live': '#e91916',
  'color-background-prime': '#0e9bd8',
  'color-background-error': '#ff8280',
  'color-background-warn': '#ffd37a',
  'color-background-success': '#00f593',
  'color-background-info': '#a3c2ff',
  'color-background-brand': '#bf94ff',
  'color-background-overlay-error': '#ff8280',
  'color-background-overlay-warn': '#ffd37a',
  'color-background-overlay-success': '#00f593',
  'color-background-overlay-info': '#a3c2ff',
  'color-background-overlay-brand': '#bf94ff',
  'color-background-interactable-hover': 'rgba(255, 255, 255, 0.2)',
  'color-background-interactable-active': 'rgba(255, 255, 255, 0.15)',
  'color-background-interactable-selected': '#9147ff',
  'color-background-interactable-overlay-hover': 'rgba(255, 255, 255, 0.2)',
  'color-background-interactable-overlay-active': 'rgba(255, 255, 255, 0.15)',
  'color-background-interactable-overlay-selected': '#ffffff',
  'color-background-interactable-destructive-hover': '#bb1411',
  'color-background-interactable-destructive-active': '#e91916',
  'color-background-button-primary-default': '#9147ff',
  'color-background-button-primary-hover': '#772ce8',
  'color-background-button-primary-active': '#9147ff',
  'color-background-button-secondary-default': 'rgba(255, 255, 255, 0.15)',
  'color-background-button-secondary-hover': 'rgba(255, 255, 255, 0.2)',
  'color-background-button-secondary-active': 'rgba(255, 255, 255, 0.15)',
  'color-background-button-text-default': 'rgba(0, 0, 0, 0)',
  'color-background-button-text-hover': 'rgba(255, 255, 255, 0.2)',
  'color-background-button-text-active': 'rgba(255, 255, 255, 0.15)',
  'color-background-button-destructive-default': '#ff4f4d',
  'color-background-button-destructive-hover': '#ffaaa8',
  'color-background-button-destructive-active': '#ff4f4d',
  'color-background-button-error': '#ff4f4d',
  'color-background-button-error-hover': '#ffaaa8',
  'color-background-button-error-active': '#ff4f4d',
  'color-background-button-warn': '#ffb31a',
  'color-background-button-warn-hover': '#ffe5b3',
  'color-background-button-warn-active': '#ffb31a',
  'color-background-button-success': '#00db84',
  'color-background-button-success-hover': '#8fffd2',
  'color-background-button-success-active': '#00db84',
  'color-background-button-info': '#7aa7ff',
  'color-background-button-info-hover': '#c7daff',
  'color-background-button-info-active': '#7aa7ff',
  'color-background-button-brand': '#9147ff',
  'color-background-button-brand-hover': '#772ce8',
  'color-background-button-brand-active': '#9147ff',
  'color-background-button-overlay-primary-default': '#ffffff',
  'color-background-button-overlay-primary-hover': 'rgba(255, 255, 255, 0.9)',
  'color-background-button-overlay-primary-active': 'rgba(255, 255, 255, 0.85)',
  'color-background-button-overlay-secondary-default':
    'rgba(255, 255, 255, 0.15)',
  'color-background-button-overlay-secondary-hover': 'rgba(255, 255, 255, 0.2)',
  'color-background-button-overlay-secondary-active':
    'rgba(255, 255, 255, 0.15)',
  'color-background-button-overlay-text-default': 'rgba(0, 0, 0, 0)',
  'color-background-button-overlay-text-hover': 'rgba(255, 255, 255, 0.2)',
  'color-background-button-overlay-text-active': 'rgba(255, 255, 255, 0.15)',
  'color-background-button-overlay-error': '#ff4f4d',
  'color-background-button-overlay-error-hover': '#ffaaa8',
  'color-background-button-overlay-error-active': '#ff4f4d',
  'color-background-button-overlay-warn': '#ffb31a',
  'color-background-button-overlay-warn-hover': '#ffe5b3',
  'color-background-button-overlay-warn-active': '#ffb31a',
  'color-background-button-overlay-success': '#00db84',
  'color-background-button-overlay-success-hover': '#8fffd2',
  'color-background-button-overlay-success-active': '#00db84',
  'color-background-button-overlay-info': '#7aa7ff',
  'color-background-button-overlay-info-hover': '#c7daff',
  'color-background-button-overlay-info-active': '#7aa7ff',
  'color-background-button-overlay-brand': '#ffffff',
  'color-background-button-overlay-brand-hover': 'rgba(255, 255, 255, 0.9)',
  'color-background-button-overlay-brand-active': '#ffffff',
  'color-background-button-icon-overlay-default': 'rgba(0, 0, 0, 0)',
  'color-background-button-icon-overlay-hover': 'rgba(255, 255, 255, 0.2)',
  'color-background-button-icon-overlay-active': 'rgba(255, 255, 255, 0.15)',
  'color-background-button-disabled': 'rgba(255, 255, 255, 0.15)',
  'color-background-button-overlay-disabled': 'rgba(255, 255, 255, 0.1)',
  'color-background-image-selector-overlay': 'rgba(0, 0, 0, 0)',
  'color-background-input': 'rgba(255, 255, 255, 0.2)',
  'color-background-input-focus': '#000000',
  'color-background-input-checked': '#772ce8',
  'color-background-input-overlay': 'rgba(0, 0, 0, 0.2)',
  'color-background-input-overlay-focus': '#000000',
  'color-background-input-checkbox-checked': '#a970ff',
  'color-background-input-checkbox-checked-background': '#000000',
  'color-background-input-checkbox-checked-background-overlay': '#000000',
  'color-background-input-checkbox-checked-overlay': '#ffffff',
  'color-background-tag-default': 'rgba(255, 255, 255, 0.15)',
  'color-background-tag-hover': 'rgba(255, 255, 255, 0.2)',
  'color-background-tag-active': 'rgba(255, 255, 255, 0.15)',
  'color-background-toggle': 'rgba(0, 0, 0, 0)',
  'color-background-toggle-handle': '#ffffff',
  'color-background-toggle-handle-checked': '#a970ff',
  'color-background-toggle-handle-overlay': '#ffffff',
  'color-background-toggle-hover': 'rgba(255, 255, 255, 0.25)',
  'color-background-toggle-focus': 'rgba(255, 255, 255, 0.25)',
  'color-background-toggle-checked': '#000000',
  'color-background-toggle-overlay': 'rgba(0, 0, 0, 0.2)',
  'color-background-toggle-overlay-checked': '#000000',
  'color-background-tooltip': '#ffffff',
  'color-background-overlay': 'rgba(0, 0, 0, 0.6)',
  'color-background-progress': 'rgba(255, 255, 255, 0.2)',
  'color-background-progress-status': '#a970ff',
  'color-background-progress-status-error': '#ff4f4d',
  'color-background-progress-status-caution': '#ffb31a',
  'color-background-progress-status-success': '#00db84',
  'color-background-progress-overlay-status': 'rgba(255, 255, 255, 0.8)',
  'color-background-progress-overlay-mask': 'rgba(0, 0, 0, 0.4)',
  'color-background-progress-countdown': 'none',
  'color-background-progress-countdown-status': '#9147ff',
  'color-background-pill': '#53535f',
  'color-background-pill-new': '#ff75e6',
  'color-background-pill-subtle': '#c8c8d0',
  'color-background-pill-notification': '#e91916',
  'color-background-range': 'rgba(255, 255, 255, 0.2)',
  'color-background-range-fill': '#a970ff',
  'color-background-range-overlay': 'rgba(255, 255, 255, 0.3)',
  'color-background-range-overlay-fill': '#ffffff',
  'color-background-social-column': '#18181b',
  'color-background-top-nav': '#451093',
  'color-background-chat': '#040109',
  'color-background-chat-alt': '#15052e',
  'color-background-chat-header': '#0d031c',
  'color-background-chat-line-mentioning': '#323239',
  'color-background-chat-line-mentioned': '#f7f7f8',
  'color-background-modal-overlay': 'rgba(0, 0, 0, 0.85)',
  'color-background-modal': '#15052e',
  'color-background-graph': '#0d031c',
  'color-background-graph-fill': '#772ce8',
  'color-background-scrollbar': '#1f1f23',
  'color-text-base': '#efeff1',
  'color-text-alt': '#dedee3',
  'color-text-alt-2': '#adadb8',
  'color-text-link': '#a970ff',
  'color-text-link-hover': '#a970ff',
  'color-text-link-active': '#a970ff',
  'color-text-link-focus': '#a970ff',
  'color-text-link-visited': '#a970ff',
  'color-text-live': '#ff8280',
  'color-text-alert': '#ff8280',
  'color-text-prime': '#0e9bd8',
  'color-text-error': '#ff8280',
  'color-text-warn': '#e69900',
  'color-text-success': '#00c274',
  'color-text-info': '#7aa7ff',
  'color-text-brand': '#bf94ff',
  'color-text-overlay-error': '#ff8280',
  'color-text-overlay-warn': '#e69900',
  'color-text-overlay-success': '#00c274',
  'color-text-overlay-info': '#7aa7ff',
  'color-text-overlay-brand': '#ffffff',
  'color-text-accessible-red': '#ff8280',
  'color-text-accessible-green': '#00c274',
  'color-text-accessible-blue': '#7aa7ff',
  'color-text-tab': '#efeff1',
  'color-text-tab-active': '#bf94ff',
  'color-text-badge-alt': '#000000',
  'color-text-badge-alt-2': '#000000',
  'color-text-button-primary': '#ffffff',
  'color-text-button-secondary': '#efeff1',
  'color-text-button-text': '#bf94ff',
  'color-text-button-destructive': '#000000',
  'color-text-button-error': '#000000',
  'color-text-button-warn': '#000000',
  'color-text-button-success': '#000000',
  'color-text-button-info': '#000000',
  'color-text-button-brand': '#ffffff',
  'color-text-button-overlay-primary': '#000000',
  'color-text-button-overlay-secondary': '#ffffff',
  'color-text-button-overlay-text': '#ffffff',
  'color-text-button-overlay-error': '#000000',
  'color-text-button-overlay-warn': '#000000',
  'color-text-button-overlay-success': '#000000',
  'color-text-button-overlay-info': '#000000',
  'color-text-button-overlay-brand': '#000000',
  'color-text-button-disabled': 'rgba(255, 255, 255, 0.5)',
  'color-text-interactable-selected': '#ffffff',
  'color-text-interactable-overlay-selected': '#000000',
  'color-text-input': '#efeff1',
  'color-text-input-placeholder': 'rgba(255, 255, 255, 0.7)',
  'color-text-input-placeholder-overlay': 'rgba(255, 255, 255, 0.7)',
  'color-text-input-checked-icon': '#ffffff',
  'color-text-label': '#f7f7f8',
  'color-text-label-optional': '#848494',
  'color-text-hint': '#848494',
  'color-text-tag': 'rgba(255, 255, 255, 0.7)',
  'color-text-toggle-checked-icon': '#a970ff',
  'color-text-toggle-checked-icon-overlay': '#ffffff',
  'color-text-tooltip': '#040109',
  'color-text-overlay': '#ffffff',
  'color-text-overlay-alt': 'rgba(255, 255, 255, 0.85)',
  'color-text-overlay-link': '#ffffff',
  'color-text-overlay-link-hover': '#e3d1ff',
  'color-text-overlay-link-active': '#e3d1ff',
  'color-text-overlay-link-focus': '#e3d1ff',
  'color-text-overlay-link-visited': '#ffffff',
  'color-text-pill': '#000000',
  'color-text-chat-line-mentioning': '#ffffff',
  'color-text-chat-line-mentioned': '#18181b',
  'color-text-channel-status-text-indicator-hosting': '#000000',
  'color-text-channel-status-text-indicator-rerun': '#000000',
  'color-text-channel-status-text-indicator-offline': '#000000',
  'color-text-channel-status-text-indicator-hosting-overlay': '#000000',
  'color-text-channel-status-text-indicator-rerun-overlay': '#000000',
  'color-text-channel-status-text-indicator-offline-overlay': '#000000',
  'color-border-base': 'rgba(255, 255, 255, 0.1)',
  'color-border-region': '#000000',
  'color-border-overlay': 'rgba(255, 255, 255, 0.25)',
  'color-border-alert': '#e91916',
  'color-border-error': '#ff4f4d',
  'color-border-warn': '#ffb31a',
  'color-border-success': '#00db84',
  'color-border-info': '#528bff',
  'color-border-brand': '#a970ff',
  'color-border-error-decorative': '#ff4f4d',
  'color-border-warn-decorative': '#ffb31a',
  'color-border-success-decorative': '#00db84',
  'color-border-info-decorative': '#528bff',
  'color-border-brand-decorative': '#a970ff',
  'color-border-overlay-error': '#ff4f4d',
  'color-border-overlay-warn': '#ffb31a',
  'color-border-overlay-success': '#00db84',
  'color-border-overlay-info': '#528bff',
  'color-border-overlay-brand': '#ffffff',
  'color-border-overlay-error-decorative': '#ff4f4d',
  'color-border-overlay-warn-decorative': '#ffb31a',
  'color-border-overlay-success-decorative': '#00db84',
  'color-border-overlay-info-decorative': '#528bff',
  'color-border-overlay-brand-decorative': '#a970ff',
  'color-border-balloon-overlay': 'rgba(255, 255, 255, 0.2)',
  'color-border-tab': 'rgba(255, 255, 255, 0.1)',
  'color-border-tab-hover': '#bf94ff',
  'color-border-tab-focus': '#bf94ff',
  'color-border-tab-active': '#a970ff',
  'color-border-image-selector': 'rgba(0, 0, 0, 0.3)',
  'color-border-image-selector-overlay': 'rgba(255, 255, 255, 0.3)',
  'color-border-image-selector-overlay-selected': '#ffffff',
  'color-border-input': 'rgba(255, 255, 255, 0.2)',
  'color-border-input-hover': 'rgba(255, 255, 255, 0.3)',
  'color-border-input-focus': '#a970ff',
  'color-border-input-error': '#ff4f4d',
  'color-border-input-overlay': 'rgba(255, 255, 255, 0.3)',
  'color-border-input-overlay-hover': 'rgba(255, 255, 255, 0.5)',
  'color-border-input-overlay-focus': '#ffffff',
  'color-border-input-checkbox': 'rgba(255, 255, 255, 0.7)',
  'color-border-input-checkbox-hover': '#ffffff',
  'color-border-input-checkbox-focus': '#a970ff',
  'color-border-input-checkbox-checked': '#a970ff',
  'color-border-input-checkbox-error': '#ff4f4d',
  'color-border-input-checkbox-overlay': 'rgba(255, 255, 255, 0.7)',
  'color-border-input-checkbox-hover-overlay': '#ffffff',
  'color-border-input-checkbox-checked-overlay': '#ffffff',
  'color-border-input-checkbox-overlay-focus': '#ffffff',
  'color-border-range-handle': '#a970ff',
  'color-border-range-handle-focus': '#ffffff',
  'color-border-tag': 'rgba(255, 255, 255, 0.15)',
  'color-border-toggle': 'rgba(255, 255, 255, 0.7)',
  'color-border-toggle-hover': '#ffffff',
  'color-border-toggle-focus': '#a970ff',
  'color-border-toggle-checked': '#a970ff',
  'color-border-toggle-overlay': 'rgba(255, 255, 255, 0.7)',
  'color-border-toggle-overlay-hover': '#ffffff',
  'color-border-toggle-overlay-focus': '#ffffff',
  'color-border-toggle-overlay-checked': '#ffffff',
  'color-border-whisper-incoming': '#a970ff',
  'color-border-whisper-outgoing': '#adadb8',
  'color-border-selectable': 'rgba(255, 255, 255, 0.15)',
  'color-border-selectable-hover': 'rgba(255, 255, 255, 0.2)',
  'color-border-selectable-hover-selected': 'rgba(0, 0, 0, 0.15)',
  'color-border-selectable-selected-outer': '#ffffff',
  'color-border-selectable-selected-inner': '#000000',
  'color-border-selectable-overlay': 'rgba(255, 255, 255, 0.15)',
  'color-border-selectable-overlay-hover': 'rgba(255, 255, 255, 0.2)',
  'color-border-selectable-overlay-selected': '#ffffff',
  'color-border-spinner': 'rgba(255, 255, 255, 0.15)',
  'color-border-spinner-fill': '#dedee3',
  'color-border-quote': '#3b3b44',
  'color-icon-input-checked': '#ffffff',
  'color-icon-input-radio-checked': '#ffffff',
  'color-fill-base': '#efeff1',
  'color-fill-current': 'currentColor',
  'color-fill-alt': '#dedee3',
  'color-fill-alt-2': '#adadb8',
  'color-fill-offline': '#53535f',
  'color-fill-hosting': '#ffd37a',
  'color-fill-live': '#e91916',
  'color-fill-alert': '#eb0400',
  'color-fill-error': '#ff4f4d',
  'color-fill-warn': '#ffb31a',
  'color-fill-success': '#00f593',
  'color-fill-info': '#528bff',
  'color-fill-brand': '#a970ff',
  'color-fill-error-overlay': '#ff4f4d',
  'color-fill-warn-overlay': '#ffb31a',
  'color-fill-success-overlay': '#00f593',
  'color-fill-info-overlay': '#528bff',
  'color-fill-brand-overlay': '#a970ff',
  'color-fill-prime': '#0e9bd8',
  'color-fill-drops': '#00f593',
  'color-fill-crate': '#00f593',
  'color-fill-range-notch': '#53535f',
  'color-fill-button-icon': '#efeff1',
  'color-fill-button-icon-hover': '#efeff1',
  'color-fill-button-icon-focus': '#efeff1',
  'color-fill-button-icon-active': '#efeff1',
  'color-fill-channel-status-text-indicator-hosting':
    'rgba(255, 255, 255, 0.7)',
  'color-fill-channel-status-text-indicator-rerun': 'rgba(255, 255, 255, 0.7)',
  'color-fill-channel-status-text-indicator-offline': '#ffffff',
  'color-fill-channel-status-text-indicator-hosting-overlay':
    'rgba(255, 255, 255, 0.7)',
  'color-fill-channel-status-text-indicator-rerun-overlay':
    'rgba(255, 255, 255, 0.7)',
  'color-fill-channel-status-text-indicator-offline-overlay': '#ffffff',
  'color-fill-presence-offline': '#adadb8',
  'color-fill-presence-invisible': '#adadb8',
  'color-fill-presence-online': '#00f593',
  'color-fill-presence-away': '#ffd37a',
  'color-fill-presence-busy': '#ff8280',
  'color-fill-presence-idle': '#ffd37a',
  'color-social-twitter': '#1da1f2',
  'color-social-facebook': '#3b5998',
  'color-social-reddit': '#ff4500',
  'color-social-snapchat': '#fffc00',
  'color-social-instagram': '#405de6',
  'color-social-youtube': '#cd201f',
  'color-social-paypal': '#009cde',
  'color-social-vk': '#45668e',
  'shadow-elevation-umbra': 0.34,
  'shadow-elevation-penumbra': 0.26,
  'shadow-elevation-ambient': 0.28,
  'shadow-elevation-1':
    '0 1px 2px rgba(0, 0, 0, 0.9), 0 0px 2px rgba(0, 0, 0, 0.9)',
  'shadow-elevation-2':
    '0 4px 8px rgba(0, 0, 0, 0.4), 0 0px 4px rgba(0, 0, 0, 0.4)',
  'shadow-elevation-3':
    '0 6px 16px rgba(0, 0, 0, 0.5), 0 0px 4px rgba(0, 0, 0, 0.4)',
  'shadow-elevation-4':
    '0 12px 32px rgba(0, 0, 0, 0.5), 0 0px 8px rgba(0, 0, 0, 0.4)',
  'shadow-elevation-5':
    '0 32px 64px rgba(0, 0, 0, 0.6), 0 0px 16px rgba(0, 0, 0, 0.4)',
  'shadow-button-focus': '0 0 6px 0 #772ce8',
  'shadow-button-active': '0 0 6px 0 #772ce8',
  'shadow-button-disabled': 'none',
  'shadow-button-overlay-focus': '0 0 6px 0 rgba(255, 255, 255, 0.3)',
  'shadow-button-overlay-active': '0 0 6px 0 rgba(255, 255, 255, 0.3)',
  'shadow-tab-focus': '0 4px 6px -4px #bf94ff',
  'shadow-balloon': '0 1px 1px rgba(0, 0, 0, 0.25)',
  'shadow-scrollbar': '0 0 1px 1px rgba(255, 255, 255, 0.25)',
};
/**
 * Map of theme tokens to their light values
 */
export const LightThemeMap = {
  'color-background-button': '#5c16c5',
  'color-background-button-hover': '#772ce8',
  'color-background-button-focus': '#772ce8',
  'color-background-button-active': '#5c16c5',
  'color-background-button-purchase': 'rgba(0, 0, 0, 0.25)',
  'color-background-button-status': '#00db84',
  'color-background-button-status-hover': '#ffaaa8',
  'color-background-button-status-focus': '#ffaaa8',
  'color-background-button-status-active': '#ff4f4d',
  'color-background-button-success-focus': '#00ad96',
  'color-background-button-alert': '#e91916',
  'color-background-button-alert-hover': '#bb1411',
  'color-background-button-alert-focus': '#bb1411',
  'color-background-button-alert-active': '#e91916',
  'color-background-button-overlay': 'rgba(0, 0, 0, 0)',
  'color-background-button-overlay-hover': 'rgba(255, 255, 255, 0.05)',
  'color-background-button-overlay-focus': 'rgba(255, 255, 255, 0.05)',
  'color-background-button-overlay-active': 'rgba(255, 255, 255, 0.1)',
  'color-background-interactable-alpha-hover': 'rgba(0, 0, 0, 0.05)',
  'color-background-interactable-alpha-active': 'rgba(0, 0, 0, 0.1)',
  'color-background-interactable-alpha-selected': 'rgba(0, 0, 0, 0.05)',
  'color-text-button': '#ffffff',
  'color-text-button-hover': '#ffffff',
  'color-text-button-focus': '#ffffff',
  'color-text-button-active': '#ffffff',
  'color-text-button-secondary-hover': '#adadb8',
  'color-text-button-secondary-focus': '#adadb8',
  'color-text-button-secondary-active': '#adadb8',
  'color-text-button-text-hover': 'rgba(92, 22, 197, 0.05)',
  'color-text-button-text-focus': 'rgba(92, 22, 197, 0.05)',
  'color-text-button-text-active': 'rgba(0, 0, 0, 0)',
  'color-text-button-status': '#ffffff',
  'color-text-button-status-hover': '#ffffff',
  'color-text-button-status-focus': '#ffffff',
  'color-text-button-status-active': '#ffffff',
  'color-text-button-success-hover': '#000000',
  'color-text-button-success-focus': '#000000',
  'color-text-button-success-active': '#000000',
  'color-text-button-alert': '#000000',
  'color-text-button-alert-hover': '#000000',
  'color-text-button-alert-focus': '#000000',
  'color-text-button-alert-active': '#000000',
  'color-text-button-overlay': '#ffffff',
  'color-text-button-overlay-hover': '#ffffff',
  'color-text-button-overlay-focus': '#ffffff',
  'color-text-button-overlay-active': '#ffffff',
  'color-text-interactable': 'currentColor',
  'color-text-interactable-hover': '#ffffff',
  'color-text-interactable-active': '#ffffff',
  'color-text-interactable-inverted': '#ffffff',
  'color-text-input-focus': 'transparent',
  'color-border-button': '#5c16c5',
  'color-border-button-hover': '#772ce8',
  'color-border-button-focus': '#9147ff',
  'color-border-button-active': '#772ce8',
  'color-border-button-disabled': 'rgba(0, 0, 0, 0.05)',
  'color-border-button-status': '#00f593',
  'color-border-button-status-hover': '#bb1411',
  'color-border-button-status-focus': '#bb1411',
  'color-border-button-status-active': '#e91916',
  'color-border-button-success': '#00f593',
  'color-border-button-success-hover': '#00f593',
  'color-border-button-success-focus': '#00f593',
  'color-border-button-success-active': '#00f593',
  'color-border-button-alert': '#e91916',
  'color-border-button-alert-hover': '#bb1411',
  'color-border-button-alert-focus': '#bb1411',
  'color-border-button-alert-active': '#e91916',
  'color-border-button-overlay': 'rgba(0, 0, 0, 0)',
  'color-border-button-overlay-hover': 'rgba(0, 0, 0, 0)',
  'color-border-button-overlay-focus': 'rgba(255, 255, 255, 0.3)',
  'color-border-button-overlay-active': 'rgba(255, 255, 255, 0.6)',
  'color-border-button-overlay-bordered': '#ffffff',
  'color-border-interactable-selected': '#9147ff',
  'shadow-input': 'inset 0 0 0 1px #dedee3',
  'shadow-input-error': '0 0 8px -2px #bb1411',
  'shadow-input-focus': '0 0 10px -2px #772ce8',
  'shadow-input-error-focus': '0 0 6px -3px #bb1411',
  'shadow-interactable-focus': '0 0 6px 1px #772ce8',
  'color-background-subscriber-stream-tag-default': '#e3d1ff',
  'color-background-subscriber-stream-tag-hover': '#f0e5ff',
  'color-background-subscriber-stream-tag-active': '#e3d1ff',
  'color-border-subscriber-stream-tag': '#a970ff',
  'color-background-body': '#f7f7f8',
  'color-background-base': '#ffffff',
  'color-background-alt': '#efeff1',
  'color-background-alt-2': '#e6e6ea',
  'color-background-float': '#ffffff',
  'color-background-accent': '#772ce8',
  'color-background-accent-alt': '#5c16c5',
  'color-background-accent-alt-2': '#451093',
  'color-background-placeholder': 'rgba(0, 0, 0, 0.05)',
  'color-background-overlay-placeholder': 'rgba(255, 255, 255, 0.15)',
  'color-background-live': '#e91916',
  'color-background-prime': '#0e9bd8',
  'color-background-error': '#ff8280',
  'color-background-warn': '#ffd37a',
  'color-background-success': '#00f593',
  'color-background-info': '#a3c2ff',
  'color-background-brand': '#bf94ff',
  'color-background-overlay-error': '#ff8280',
  'color-background-overlay-warn': '#ffd37a',
  'color-background-overlay-success': '#00f593',
  'color-background-overlay-info': '#a3c2ff',
  'color-background-overlay-brand': '#bf94ff',
  'color-background-interactable-hover': 'rgba(0, 0, 0, 0.1)',
  'color-background-interactable-active': 'rgba(0, 0, 0, 0.05)',
  'color-background-interactable-selected': '#9147ff',
  'color-background-interactable-overlay-hover': 'rgba(255, 255, 255, 0.2)',
  'color-background-interactable-overlay-active': 'rgba(255, 255, 255, 0.15)',
  'color-background-interactable-overlay-selected': '#ffffff',
  'color-background-interactable-destructive-hover': '#bb1411',
  'color-background-interactable-destructive-active': '#e91916',
  'color-background-button-primary-default': '#9147ff',
  'color-background-button-primary-hover': '#772ce8',
  'color-background-button-primary-active': '#9147ff',
  'color-background-button-secondary-default': 'rgba(0, 0, 0, 0.05)',
  'color-background-button-secondary-hover': 'rgba(0, 0, 0, 0.1)',
  'color-background-button-secondary-active': 'rgba(0, 0, 0, 0.05)',
  'color-background-button-text-default': 'rgba(0, 0, 0, 0)',
  'color-background-button-text-hover': 'rgba(0, 0, 0, 0.1)',
  'color-background-button-text-active': 'rgba(0, 0, 0, 0.05)',
  'color-background-button-destructive-default': '#ff4f4d',
  'color-background-button-destructive-hover': '#ffaaa8',
  'color-background-button-destructive-active': '#ff4f4d',
  'color-background-button-error': '#ff4f4d',
  'color-background-button-error-hover': '#ffaaa8',
  'color-background-button-error-active': '#ff4f4d',
  'color-background-button-warn': '#ffb31a',
  'color-background-button-warn-hover': '#ffe5b3',
  'color-background-button-warn-active': '#ffb31a',
  'color-background-button-success': '#00db84',
  'color-background-button-success-hover': '#8fffd2',
  'color-background-button-success-active': '#00db84',
  'color-background-button-info': '#7aa7ff',
  'color-background-button-info-hover': '#c7daff',
  'color-background-button-info-active': '#7aa7ff',
  'color-background-button-brand': '#9147ff',
  'color-background-button-brand-hover': '#772ce8',
  'color-background-button-brand-active': '#9147ff',
  'color-background-button-overlay-primary-default': '#ffffff',
  'color-background-button-overlay-primary-hover': 'rgba(255, 255, 255, 0.9)',
  'color-background-button-overlay-primary-active': 'rgba(255, 255, 255, 0.85)',
  'color-background-button-overlay-secondary-default':
    'rgba(255, 255, 255, 0.15)',
  'color-background-button-overlay-secondary-hover': 'rgba(255, 255, 255, 0.2)',
  'color-background-button-overlay-secondary-active':
    'rgba(255, 255, 255, 0.15)',
  'color-background-button-overlay-text-default': 'rgba(0, 0, 0, 0)',
  'color-background-button-overlay-text-hover': 'rgba(255, 255, 255, 0.2)',
  'color-background-button-overlay-text-active': 'rgba(255, 255, 255, 0.15)',
  'color-background-button-overlay-error': '#ff4f4d',
  'color-background-button-overlay-error-hover': '#ffaaa8',
  'color-background-button-overlay-error-active': '#ff4f4d',
  'color-background-button-overlay-warn': '#ffb31a',
  'color-background-button-overlay-warn-hover': '#ffe5b3',
  'color-background-button-overlay-warn-active': '#ffb31a',
  'color-background-button-overlay-success': '#00db84',
  'color-background-button-overlay-success-hover': '#8fffd2',
  'color-background-button-overlay-success-active': '#00db84',
  'color-background-button-overlay-info': '#7aa7ff',
  'color-background-button-overlay-info-hover': '#c7daff',
  'color-background-button-overlay-info-active': '#7aa7ff',
  'color-background-button-overlay-brand': '#ffffff',
  'color-background-button-overlay-brand-hover': 'rgba(255, 255, 255, 0.9)',
  'color-background-button-overlay-brand-active': '#ffffff',
  'color-background-button-icon-overlay-default': 'rgba(0, 0, 0, 0)',
  'color-background-button-icon-overlay-hover': 'rgba(255, 255, 255, 0.2)',
  'color-background-button-icon-overlay-active': 'rgba(255, 255, 255, 0.15)',
  'color-background-button-disabled': 'rgba(0, 0, 0, 0.05)',
  'color-background-button-overlay-disabled': 'rgba(255, 255, 255, 0.1)',
  'color-background-image-selector-overlay': 'rgba(0, 0, 0, 0)',
  'color-background-input': 'rgba(0, 0, 0, 0.1)',
  'color-background-input-focus': '#ffffff',
  'color-background-input-checked': '#772ce8',
  'color-background-input-overlay': 'rgba(0, 0, 0, 0.2)',
  'color-background-input-overlay-focus': '#000000',
  'color-background-input-checkbox-checked': '#772ce8',
  'color-background-input-checkbox-checked-background': '#ffffff',
  'color-background-input-checkbox-checked-background-overlay': '#000000',
  'color-background-input-checkbox-checked-overlay': '#ffffff',
  'color-background-tag-default': 'rgba(0, 0, 0, 0.05)',
  'color-background-tag-hover': 'rgba(0, 0, 0, 0.1)',
  'color-background-tag-active': 'rgba(0, 0, 0, 0.05)',
  'color-background-toggle': 'rgba(0, 0, 0, 0)',
  'color-background-toggle-handle': '#000000',
  'color-background-toggle-handle-checked': '#772ce8',
  'color-background-toggle-handle-overlay': '#ffffff',
  'color-background-toggle-hover': 'rgba(0, 0, 0, 0.6)',
  'color-background-toggle-focus': 'rgba(0, 0, 0, 0.4)',
  'color-background-toggle-checked': '#ffffff',
  'color-background-toggle-overlay': 'rgba(0, 0, 0, 0.2)',
  'color-background-toggle-overlay-checked': '#000000',
  'color-background-tooltip': '#040109',
  'color-background-overlay': 'rgba(0, 0, 0, 0.6)',
  'color-background-progress': '#dedee3',
  'color-background-progress-status': '#772ce8',
  'color-background-progress-status-error': '#bb1411',
  'color-background-progress-status-caution': '#7c570e',
  'color-background-progress-status-success': '#016b40',
  'color-background-progress-overlay-status': 'rgba(255, 255, 255, 0.8)',
  'color-background-progress-overlay-mask': 'rgba(0, 0, 0, 0.4)',
  'color-background-progress-countdown': 'none',
  'color-background-progress-countdown-status': '#772ce8',
  'color-background-pill': '#53535f',
  'color-background-pill-new': '#ff75e6',
  'color-background-pill-subtle': '#c8c8d0',
  'color-background-pill-notification': '#e91916',
  'color-background-range': 'rgba(0, 0, 0, 0.2)',
  'color-background-range-fill': '#772ce8',
  'color-background-range-overlay': 'rgba(255, 255, 255, 0.3)',
  'color-background-range-overlay-fill': '#ffffff',
  'color-background-social-column': '#f7f7f8',
  'color-background-top-nav': '#5c16c5',
  'color-background-chat': '#f7f7f8',
  'color-background-chat-alt': '#efeff1',
  'color-background-chat-header': '#f7f7f8',
  'color-background-chat-line-mentioning': '#dedee3',
  'color-background-chat-line-mentioned': '#0e0e10',
  'color-background-modal-overlay': 'rgba(0, 0, 0, 0.85)',
  'color-background-modal': '#ffffff',
  'color-background-graph': '#fcfaff',
  'color-background-graph-fill': '#9147ff',
  'color-background-scrollbar': 'rgba(0, 0, 0, 0.15)',
  'color-text-base': '#0e0e10',
  'color-text-alt': '#1f1f23',
  'color-text-alt-2': '#53535f',
  'color-text-link': '#772ce8',
  'color-text-link-hover': '#9147ff',
  'color-text-link-active': '#9147ff',
  'color-text-link-focus': '#9147ff',
  'color-text-link-visited': '#9147ff',
  'color-text-live': '#971311',
  'color-text-alert': '#971311',
  'color-text-prime': '#0e9bd8',
  'color-text-error': '#971311',
  'color-text-warn': '#65470b',
  'color-text-success': '#0a5738',
  'color-text-info': '#1345aa',
  'color-text-brand': '#5c16c5',
  'color-text-overlay-error': '#ff8280',
  'color-text-overlay-warn': '#e69900',
  'color-text-overlay-success': '#00c274',
  'color-text-overlay-info': '#7aa7ff',
  'color-text-overlay-brand': '#ffffff',
  'color-text-accessible-red': '#971311',
  'color-text-accessible-green': '#0a5738',
  'color-text-accessible-blue': '#1345aa',
  'color-text-tab': '#0e0e10',
  'color-text-tab-active': '#772ce8',
  'color-text-badge-alt': '#ffffff',
  'color-text-badge-alt-2': '#ffffff',
  'color-text-button-primary': '#ffffff',
  'color-text-button-secondary': '#0e0e10',
  'color-text-button-text': '#5c16c5',
  'color-text-button-destructive': '#000000',
  'color-text-button-error': '#000000',
  'color-text-button-warn': '#000000',
  'color-text-button-success': '#000000',
  'color-text-button-info': '#000000',
  'color-text-button-brand': '#ffffff',
  'color-text-button-overlay-primary': '#000000',
  'color-text-button-overlay-secondary': '#ffffff',
  'color-text-button-overlay-text': '#ffffff',
  'color-text-button-overlay-error': '#000000',
  'color-text-button-overlay-warn': '#000000',
  'color-text-button-overlay-success': '#000000',
  'color-text-button-overlay-info': '#000000',
  'color-text-button-overlay-brand': '#000000',
  'color-text-button-disabled': 'rgba(0, 0, 0, 0.3)',
  'color-text-interactable-selected': '#ffffff',
  'color-text-interactable-overlay-selected': '#0e0e10',
  'color-text-input': '#0e0e10',
  'color-text-input-placeholder': 'rgba(0, 0, 0, 0.7)',
  'color-text-input-placeholder-overlay': 'rgba(255, 255, 255, 0.7)',
  'color-text-input-checked-icon': '#ffffff',
  'color-text-label': '#18181b',
  'color-text-label-optional': '#53535f',
  'color-text-hint': '#53535f',
  'color-text-tag': 'rgba(0, 0, 0, 0.7)',
  'color-text-toggle-checked-icon': '#772ce8',
  'color-text-toggle-checked-icon-overlay': '#ffffff',
  'color-text-tooltip': '#ffffff',
  'color-text-overlay': '#ffffff',
  'color-text-overlay-alt': 'rgba(255, 255, 255, 0.85)',
  'color-text-overlay-link': '#ffffff',
  'color-text-overlay-link-hover': '#e3d1ff',
  'color-text-overlay-link-active': '#e3d1ff',
  'color-text-overlay-link-focus': '#e3d1ff',
  'color-text-overlay-link-visited': '#ffffff',
  'color-text-pill': '#000000',
  'color-text-chat-line-mentioning': '#18181b',
  'color-text-chat-line-mentioned': '#ffffff',
  'color-text-channel-status-text-indicator-hosting': '#ffffff',
  'color-text-channel-status-text-indicator-rerun': '#ffffff',
  'color-text-channel-status-text-indicator-offline': '#ffffff',
  'color-text-channel-status-text-indicator-hosting-overlay': '#000000',
  'color-text-channel-status-text-indicator-rerun-overlay': '#000000',
  'color-text-channel-status-text-indicator-offline-overlay': '#000000',
  'color-border-base': 'rgba(0, 0, 0, 0.1)',
  'color-border-region': '#e6e6ea',
  'color-border-overlay': 'rgba(255, 255, 255, 0.25)',
  'color-border-alert': '#e91916',
  'color-border-error': '#bb1411',
  'color-border-warn': '#7c570e',
  'color-border-success': '#016b40',
  'color-border-info': '#1756d3',
  'color-border-brand': '#772ce8',
  'color-border-error-decorative': '#ff4f4d',
  'color-border-warn-decorative': '#ffb31a',
  'color-border-success-decorative': '#00db84',
  'color-border-info-decorative': '#528bff',
  'color-border-brand-decorative': '#9147ff',
  'color-border-overlay-error': '#ff4f4d',
  'color-border-overlay-warn': '#ffb31a',
  'color-border-overlay-success': '#00db84',
  'color-border-overlay-info': '#528bff',
  'color-border-overlay-brand': '#ffffff',
  'color-border-overlay-error-decorative': '#ff4f4d',
  'color-border-overlay-warn-decorative': '#ffb31a',
  'color-border-overlay-success-decorative': '#00db84',
  'color-border-overlay-info-decorative': '#528bff',
  'color-border-overlay-brand-decorative': '#a970ff',
  'color-border-balloon-overlay': 'rgba(255, 255, 255, 0.2)',
  'color-border-tab': 'rgba(0, 0, 0, 0.1)',
  'color-border-tab-hover': '#9147ff',
  'color-border-tab-focus': '#9147ff',
  'color-border-tab-active': '#772ce8',
  'color-border-image-selector': 'rgba(0, 0, 0, 0.3)',
  'color-border-image-selector-overlay': 'rgba(255, 255, 255, 0.3)',
  'color-border-image-selector-overlay-selected': '#ffffff',
  'color-border-input': 'rgba(0, 0, 0, 0.1)',
  'color-border-input-hover': 'rgba(0, 0, 0, 0.2)',
  'color-border-input-focus': '#772ce8',
  'color-border-input-error': '#bb1411',
  'color-border-input-overlay': 'rgba(255, 255, 255, 0.3)',
  'color-border-input-overlay-hover': 'rgba(255, 255, 255, 0.5)',
  'color-border-input-overlay-focus': '#ffffff',
  'color-border-input-checkbox': 'rgba(0, 0, 0, 0.7)',
  'color-border-input-checkbox-hover': '#000000',
  'color-border-input-checkbox-focus': '#772ce8',
  'color-border-input-checkbox-checked': '#772ce8',
  'color-border-input-checkbox-error': '#bb1411',
  'color-border-input-checkbox-overlay': 'rgba(255, 255, 255, 0.7)',
  'color-border-input-checkbox-hover-overlay': '#ffffff',
  'color-border-input-checkbox-checked-overlay': '#ffffff',
  'color-border-input-checkbox-overlay-focus': '#ffffff',
  'color-border-range-handle': '#772ce8',
  'color-border-range-handle-focus': '#000000',
  'color-border-tag': 'rgba(0, 0, 0, 0.05)',
  'color-border-toggle': 'rgba(0, 0, 0, 0.7)',
  'color-border-toggle-hover': '#000000',
  'color-border-toggle-focus': '#772ce8',
  'color-border-toggle-checked': '#772ce8',
  'color-border-toggle-overlay': 'rgba(255, 255, 255, 0.7)',
  'color-border-toggle-overlay-hover': '#ffffff',
  'color-border-toggle-overlay-focus': '#ffffff',
  'color-border-toggle-overlay-checked': '#ffffff',
  'color-border-whisper-incoming': '#a970ff',
  'color-border-whisper-outgoing': '#adadb8',
  'color-border-selectable': 'rgba(0, 0, 0, 0.05)',
  'color-border-selectable-hover': 'rgba(0, 0, 0, 0.1)',
  'color-border-selectable-hover-selected': 'rgba(0, 0, 0, 0.15)',
  'color-border-selectable-selected-outer': '#000000',
  'color-border-selectable-selected-inner': '#ffffff',
  'color-border-selectable-overlay': 'rgba(255, 255, 255, 0.15)',
  'color-border-selectable-overlay-hover': 'rgba(255, 255, 255, 0.2)',
  'color-border-selectable-overlay-selected': '#ffffff',
  'color-border-spinner': 'rgba(0, 0, 0, 0.15)',
  'color-border-spinner-fill': '#18181b',
  'color-border-quote': '#53535f',
  'color-icon-input-checked': '#ffffff',
  'color-icon-input-radio-checked': '#ffffff',
  'color-fill-base': '#0e0e10',
  'color-fill-current': 'currentColor',
  'color-fill-alt': '#1f1f23',
  'color-fill-alt-2': '#53535f',
  'color-fill-offline': '#adadb8',
  'color-fill-hosting': '#ffd37a',
  'color-fill-live': '#e91916',
  'color-fill-alert': '#eb0400',
  'color-fill-error': '#eb0400',
  'color-fill-warn': '#9e6900',
  'color-fill-success': '#018852',
  'color-fill-info': '#1f69ff',
  'color-fill-brand': '#9147ff',
  'color-fill-error-overlay': '#ff4f4d',
  'color-fill-warn-overlay': '#ffb31a',
  'color-fill-success-overlay': '#00f593',
  'color-fill-info-overlay': '#528bff',
  'color-fill-brand-overlay': '#a970ff',
  'color-fill-prime': '#0e9bd8',
  'color-fill-drops': '#00f593',
  'color-fill-crate': '#00f593',
  'color-fill-range-notch': '#adadb8',
  'color-fill-button-icon': '#0e0e10',
  'color-fill-button-icon-hover': '#0e0e10',
  'color-fill-button-icon-focus': '#0e0e10',
  'color-fill-button-icon-active': '#0e0e10',
  'color-fill-channel-status-text-indicator-hosting': 'rgba(0, 0, 0, 0.7)',
  'color-fill-channel-status-text-indicator-rerun': 'rgba(0, 0, 0, 0.7)',
  'color-fill-channel-status-text-indicator-offline': '#000000',
  'color-fill-channel-status-text-indicator-hosting-overlay':
    'rgba(255, 255, 255, 0.7)',
  'color-fill-channel-status-text-indicator-rerun-overlay':
    'rgba(255, 255, 255, 0.7)',
  'color-fill-channel-status-text-indicator-offline-overlay': '#ffffff',
  'color-fill-presence-offline': '#848494',
  'color-fill-presence-invisible': '#848494',
  'color-fill-presence-online': '#00f593',
  'color-fill-presence-away': '#ffd37a',
  'color-fill-presence-busy': '#971311',
  'color-fill-presence-idle': '#ffd37a',
  'color-social-twitter': '#1da1f2',
  'color-social-facebook': '#3b5998',
  'color-social-reddit': '#ff4500',
  'color-social-snapchat': '#fffc00',
  'color-social-instagram': '#405de6',
  'color-social-youtube': '#cd201f',
  'color-social-paypal': '#009cde',
  'color-social-vk': '#45668e',
  'shadow-elevation-umbra': 0.1,
  'shadow-elevation-penumbra': 0.02,
  'shadow-elevation-ambient': 0.04,
  'shadow-elevation-1':
    '0 1px 2px rgba(0, 0, 0, 0.15), 0 0px 2px rgba(0, 0, 0, 0.1)',
  'shadow-elevation-2':
    '0 4px 8px rgba(0, 0, 0, 0.2), 0 0px 4px rgba(0, 0, 0, 0.05)',
  'shadow-elevation-3':
    '0 6px 16px rgba(0, 0, 0, 0.2), 0 0px 4px rgba(0, 0, 0, 0.05)',
  'shadow-elevation-4':
    '0 12px 32px rgba(0, 0, 0, 0.2), 0 0px 8px rgba(0, 0, 0, 0.05)',
  'shadow-elevation-5':
    '0 32px 64px rgba(0, 0, 0, 0.2), 0 0px 16px rgba(0, 0, 0, 0.05)',
  'shadow-button-focus': '0 0 6px 0 #772ce8',
  'shadow-button-active': '0 0 6px 0 #772ce8',
  'shadow-button-disabled': 'none',
  'shadow-button-overlay-focus': '0 0 6px 0 rgba(255, 255, 255, 0.3)',
  'shadow-button-overlay-active': '0 0 6px 0 rgba(255, 255, 255, 0.3)',
  'shadow-tab-focus': '0 4px 6px -4px #772ce8',
  'shadow-balloon': '0 1px 1px rgba(0, 0, 0, 0.25)',
  'shadow-scrollbar': '0 0 1px 1px rgba(255, 255, 255, 0.25)',
};
/**
 * Map of themes to maps of theme token names with values, allowing theme-dynamic lookups
 */
export const DynamicThemeMap = {
  dark: DarkThemeMap,
  light: LightThemeMap,
};
/**
 * All themes currently supported by Core UI
 */
export const THEMES = ['dark', 'light'];

export type Theme = 'light' | 'dark';

export type ThemeToken = keyof typeof LightThemeMap;

export type StaticToken =  keyof typeof StaticTokenMap;